theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "custom"
command = "echo TwitchyLinux"
interval = "once"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 4

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"
