#!/bin/bash
# Installer startup for TwitchyLinux.
set +e

# https://www.reddit.com/r/swaywm/comments/do3g91/native_wayland_setup_for_arch/f5ka2nm/
export CLUTTER_BACKEND=wayland
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ACCEL=gl
export ELM_DISPLAY=wl
export QT_QPA_PLATFORM=wayland
export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1

install -d -m 0755 -o twl -g twl /tmp/installer-xdg
export XDG_RUNTIME_DIR=/tmp/installer-xdg

export WLR_DIRECT_TTY=/dev/tty0
export WLR_SESSION=direct
sudo -E -u twl dbus-run-session sway -c /usr/share/twlinst/sway.config &

while [[ ! -e "${XDG_RUNTIME_DIR}/wayland-0" ]]
do
  sleep 1
  echo "Waiting for wayland socket to come up"
done

cd /usr/share/twlinst
/usr/share/twlinst/twlinst --version VERSION_MARKER
rc=$?; if [[ $rc == 0 ]]; then shutdown -h 0; fi
