theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 4

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "sound"
