[post_base.install.containerd]
if.all = ["features.SWE"]
if.not = ["features.essential"]
order_priority = 88
do = [
  {action = 'mkdir', dir = '/containerd-scripts'},
  {action = 'install-resource', from = 'containerd/build-libseccomp.sh', to = '/containerd-scripts/build-libseccomp.sh'},
  {action = 'install-resource', from = 'containerd/install-containerd.sh', to = '/containerd-scripts/install-containerd.sh'},
  {action = 'run', bin = 'bash', args = ['/containerd-scripts/install-containerd.sh']},
  {action = 'run', bin = 'rm', args = ['-rf', '/containerd-scripts']},
]
