[base]
debian.track = "testing"
debian.url = "http://deb.debian.org/debian/"

[base.locale]
area = "America"
zone = "Los_Angeles"
generate_locales = ["en_US.UTF-8 UTF-8", "en_US ISO-8859-1"]
default = "en_US.UTF-8"

[base.linux]
version = "5.6.19"
url = "https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.6.19.tar.xz"
sha256 = "62532fb257fe98a68601e4ca36bd3d34300b4f26f447bf495df4693442601ee8"
build_packages = ["build-essential", "fakeroot", "devscripts", "wget", "libncurses-dev"]

[base.release_info]
name = "TwitchyLinux (/w Debian GNU/Linux)"
pretty_name = "TwitchyLinux (Debian GNU/Linux stable derivative)"
id = "twitchylinux"
url = "https://github.com/TwitchyLinux"
issue = "TwitchyLinux (/w GNU/Linux on Debian buster) \\n \\l"

[base.main_user]
name = 'twl'
default_password = 'twl'
groups = ['sudo', 'systemd-journal', 'netdev']
