[graphical_environment]
packages = [
  "gdm3", "adwaita-icon-theme", "at-spi2-core", "baobab", "caribou", "dconf-cli", "dconf-gsettings-backend", "eog", "evince",
  "fonts-cantarell", "gedit", "glib-networking", "gnome-backgrounds", "gnome-bluetooth", "gnome-calculator", "gnome-characters", "gnome-control-center",
  "gnome-disk-utility", "gnome-font-viewer", "gnome-keyring", "gnome-logs", "gnome-menus", "gnome-session", "gnome-shell", "gnome-settings-daemon",
  "gnome-shell-extensions", "gnome-system-monitor", "gnome-terminal", "gsettings-desktop-schemas", "gstreamer1.0-packagekit", "gstreamer1.0-plugins-base",
  "gstreamer1.0-plugins-good", "gstreamer1.0-pulseaudio", "gvfs-backends", "gvfs-fuse", "libatk-adaptor", "libcanberra-pulse", "libglib2.0-bin",
  "libpam-gnome-keyring", "libproxy1-plugin-gsettings", "libproxy1-plugin-webkit", "nautilus", "pulseaudio", "pulseaudio-module-bluetooth",
  "sound-theme-freedesktop", "system-config-printer-common", "system-config-printer-udev", "totem", "zenity", "libproxy1-plugin-networkmanager",
  "network-manager-gnome"
]

[graphical_environment.post.install.nmap-tools]
order_priority = 20
packages = ["nmap", "ncat", "ndiff", "zenmap"]

[graphical_environment.post.install.gui-dev-tools]
order_priority = 10
packages = ["gpick", "glade", "mesa-utils", "libgtk-3-dev", "libcairo2-dev", "libglib2.0-dev"]
