[graphical_environment.post.install.non-latin-fonts]
order_priority = 95
packages = ["fonts-indic", "fonts-noto", "fonts-noto-cjk"]

[graphical_environment.post.install.nmap-tools]
order_priority = 90
packages = ["nmap", "ncat", "ndiff", "zenmap"]

[graphical_environment.post.install.gui-dev-tools]
order_priority = 85
packages = ["gpick", "glade", "mesa-utils", "libgtk-3-dev", "libcairo2-dev", "libglib2.0-dev", "libwxgtk3.0-dev"]

[graphical_environment.post.install.cad-and-images]
order_priority = 80
packages = ["openscad", "inkscape"]

[graphical_environment.post.install.qemu-gui]
order_priority = 80
packages = ["qemu-system-gui"]

[graphical_environment.post.install.wireshark]
order_priority = 75
packages = ["wireshark"]

[graphical_environment.post.install.chrome]
order_priority = 50
do = [
  {action = 'download', url = 'https://dl.google.com/linux/linux_signing_key.pub', to = '/chrome-signing-key.pub'},
  {action = 'run', bin = 'apt-key', args = ['add', '/chrome-signing-key.pub']},
  {action = 'mkdir', dir = '/etc/apt/sources.list.d'},
  {action = 'append', to = '/etc/apt/sources.list.d/google-chrome.list', data = "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\n"},
  {action = 'run', bin = 'rm', args = ['/chrome-signing-key.pub']},
  {action = 'run', bin = 'apt-get', args = ['update']},
  {action = 'run', bin = 'apt-get', args = ['-y', 'install', 'google-chrome-stable']},
]

[graphical_environment.post.install.atom]
order_priority = 45
do = [
  {action = 'download', url = 'https://packagecloud.io/AtomEditor/atom/gpgkey', to = '/atom-signing-key.pub'},
  {action = 'run', bin = 'apt-key', args = ['add', '/atom-signing-key.pub']},
  {action = 'append', to = '/etc/apt/sources.list', data = "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main\n"},
  {action = 'run', bin = 'rm', args = ['/atom-signing-key.pub']},
  {action = 'run', bin = 'apt-get', args = ['update']},
  {action = 'run', bin = 'apt-get', args = ['-y', 'install', 'atom']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '/usr/bin/apm install file-icons']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '/usr/bin/apm install language-systemd']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '/usr/bin/apm install go-plus']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '/usr/bin/apm install atom-beautify']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '/usr/bin/apm install language-ccr']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '/usr/bin/apm install language-hcl']},
]
