[post_base.install.fs-tools]
packages = ["e2fsprogs", "e2fsck-static", "gpart", "parted", "kpartx",
"libfuse2", "ntfs-3g", "fuse2fs", "fuseiso", "fatcat", "fatattr", "exfat-utils", "exfat-fuse",
"cpio", "disktype", "cpio-doc", "multipath-tools", "smartmontools", "dosfstools",
"sg3-utils", "squashfs-tools", "libext2fs2", "apt-file"]
order_priority = 100

[post_base.install.net-tools]
packages = ["curl", "curlftpfs", "net-tools", "netbase", "netcat-openbsd", "netwox",
"iproute2", "iproute2-doc", "tcpdump", "tcpstat", "traceroute",
"inetutils-ftp", "inetutils-ping", "inetutils-tools",
"arping", "arptables", "dnsutils", "irssi"]
order_priority = 99

[post_base.install.compression-tools]
order_priority = 99
packages = ["lzip", "unzip", "zip", "tar", "rar", "unrar"]

[post_base.install.essential-cli-tools]
order_priority = 98
packages = [
  "nano", "vim", "vim-doc",
  "dstat", "info", "attr",
]

[post_base.install.cli-tools]
if.not = ["features.essential"]
order_priority = 98
packages = [
  "htop", "screen", "tmux", "minicom",
  "git", "git-doc", "subversion", "subversion-tools",
  "lua5.2", "python2.7", "python-pip", "python-numpy", "python-dev", "python-numpy-doc", "python3", "python3-numpy",
  "figlet",
  "sharutils", "sharutils-doc",
  "pm-utils", "pciutils", "sysstat", "dpkg-dev",
  "gnupg", "jq", "tidy",
  "bubblewrap",
  "asciidoc",
]

[post_base.install.usb]
if.not = ["features.essential"]
order_priority = 90
packages = ["usbutils", "libusb-1.0-0", "libusb-1.0-0-dev", "libusb-1.0-doc"]
