[post_base.install.sudo]
order_priority = 85
packages = ["sudo"]

[post_base.install.wifi]
if.not = ["features.essential"]
order_priority = 84
packages = ["iw", "wireless-tools", "wpasupplicant", "rfkill", "net-tools"]

[post_base.install.v4l2loopback]
if.any = ["features.av"]
order_priority = 83
packages = ["help2man"]
do = [
  {action = 'download', url = 'https://github.com/umlaeute/v4l2loopback/archive/v0.12.5.tar.gz', to = '/v4l2loopback.tar.gz'},
  {action = 'mkdir', dir = '/v4l2loopback'},
  {action = 'run', bin = 'tar', args = ['-C', '/v4l2loopback', '-xzf', '/v4l2loopback.tar.gz']},
  {action = 'run', bin = 'rm', args = ['/v4l2loopback.tar.gz']},
  {action = 'run', bin = 'make', env = {KERNELRELEASE = '{{base.linux.version}}'}, args = ['-C', '/v4l2loopback/v4l2loopback-0.12.5']},
  {action = 'run', bin = 'make', env = {KERNELRELEASE = '{{base.linux.version}}'}, args = ['-C', '/v4l2loopback/v4l2loopback-0.12.5', 'install-all']},
  {action = 'run', bin = 'rm', args = ['-rf', '/v4l2loopback']},
]

[post_base.install.bash-completion]
order_priority = 80
packages = ["bash-completion", "bash-doc", "bash-builtins"]

[post_base.install.cryptsetup]
if.not = ["features.essential"]
order_priority = 20
packages = ["cryptsetup", "kbd", "console-setup", "keyutils"]

[post_base.install.mac]
order_priority = 20
packages = ["apparmor", "apparmor-utils", "auditd", "libapparmor-dev"]

[post_base.install.firmware]
if.not = ["features.essential"]
order_priority = 18
packages = [
  "firmware-iwlwifi", "firmware-atheros", "firmware-brcm80211",
  "firmware-libertas", "firmware-realtek",
  "firmware-cavium", "firmware-intel-sound", "intel-microcode",  "amd64-microcode",
  "firmware-misc-nonfree", "firmware-linux-free",
  "firmware-zd1211", "firmware-amd-graphics",
]
