[post_base.install.ffmpeg]
if.any = ["features.av"]
order_priority = 88
packages = ["ffmpeg", "ffmpeg-doc", "libavcodec-dev", "libavdevice-dev", "libavdevice58", "libavfilter-dev"]

[post_base.install.qemu]
if.not = ["features.essential"]
order_priority = 88
packages = ["libqcow-utils", "qemu-utils", "qemu-user", "qemu-kvm", "qemu-system-arm", "qemu-system-x86"]

[post_base.install.tor]
if.not = ["features.essential"]
order_priority = 88
packages = ["tor", "nyx", "torsocks"]
do = [
  {action = 'run', bin = 'systemctl', args = ['disable', 'tor.service']},
]
