[post_base.install.fs-tools]
packages = ["e2fsprogs", "e2fsck-static", "gpart", "parted", "kpartx",
"libfuse2", "ntfs-3g", "fuse2fs", "fuseiso", "fatcat", "fatattr", "exfat-utils", "exfat-fuse",
"cpio", "disktype", "cpio-doc", "multipath-tools", "smartmontools", "dosfstools",
"sg3-utils", "squashfs-tools", "libext2fs2", "apt-file"]
order_priority = 100

[post_base.install.net-tools]
packages = ["curl", "curlftpfs", "net-tools", "netbase", "netcat-openbsd", "netwox",
"iproute2", "iproute2-doc", "tcpdump", "tcpstat", "traceroute",
"inetutils-ftp", "inetutils-ping", "inetutils-tools",
"arping", "arptables", "dnsutils", "irssi"]
order_priority = 99

[post_base.install.compression-tools]
order_priority = 99
packages = ["lzip", "unzip", "zip", "tar", "rar", "unrar"]

[post_base.install.cli-tools]
if.not = ["features.essential"]
order_priority = 98
packages = [
  "htop", "screen", "tmux", "minicom",
  "nano", "vim", "vim-doc",
  "git", "git-doc", "subversion", "subversion-tools",
  "lua5.2", "python2.7", "python-pip", "python-numpy", "python-dev", "python-numpy-doc", "python3", "python3-numpy",
  "figlet",
  "sharutils", "sharutils-doc",
  "pm-utils", "pciutils", "sysstat", "dpkg-dev",
  "gnupg", "jq", "tidy", "dstat", "info", "attr",
  "bubblewrap",
  "asciidoc",
]

[post_base.install.usb]
if.not = ["features.essential"]
order_priority = 90
packages = ["usbutils", "libusb-1.0-0", "libusb-1.0-0-dev", "libusb-1.0-doc"]

[post_base.install.c-toolchain]
if.not = ["features.essential"]
order_priority = 90
packages = ["build-essential", "cmake", "sqlite3", "libsqlite3-0", "libsqlite3-dev", "sqlite3-doc"]

[post_base.install.c-toolchain-arm]
if.not = ["features.essential"]
order_priority = 90
packages = ["gcc-arm-none-eabi"]

[post_base.install.rust]
if.not = ["features.essential"]
order_priority = 89
do = [
  {action = 'download', url = 'https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init', to = '/rustup-init'},
  {action = 'run', bin = 'chmod', args = ['+x', '/rustup-init']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '/rustup-init --verbose --no-modify-path -y --default-toolchain stable']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '.cargo/bin/rustup target add thumbv7em-none-eabihf']},
  {action = 'run', bin = 'runuser', args = ['-l', '{{base.main_user.name}}', '-c', '.cargo/bin/rustup target add thumbv6m-none-eabi']},
  {action = 'run', bin = 'rm', args = ['/rustup-init']},
  # TODO: Make username agnostic in below command.
  {action = 'append', to = '/home/twl/.bashrc', data = "\n# Start rustup section\nsource $HOME/.cargo/env\n# End rustup section\n"},
]

[post_base.install.golang]
if.not = ["features.essential"]
order_priority = 89
do = [
  {action = 'download', url = 'https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz', to = '/go1.13.8.linux-amd64.tar.gz'},
  {action = 'sha256sum', from = '/go1.13.8.linux-amd64.tar.gz', expected = '0567734d558aef19112f2b2873caa0c600f1b4a5827930eb5a7f35235219e9d8'},
  {action = 'run', bin = 'tar', args = ['-v', '-C', '/usr/local', '-xzf', '/go1.13.8.linux-amd64.tar.gz']},
  {action = 'run', bin = 'rm', args = ['/go1.13.8.linux-amd64.tar.gz']},
  {action = 'append', to = '/etc/profile.d/golang.sh', data = "# Make Go tools available via path\nexport PATH=$PATH:/usr/local/go/bin\n"},
]

[post_base.install.protoc]
if.not = ["features.essential"]
order_priority = 88
do = [
  {action = 'download', url = 'https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip', to = '/protoc-3.11.4.zip'},
  {action = 'sha256sum', from = '/protoc-3.11.4.zip', expected = '6d0f18cd84b918c7b3edd0203e75569e0c8caecb1367bbbe409b45e28514f5be'},
  {action = 'run', bin = 'unzip', args = ['/protoc-3.11.4.zip', '-d', '/usr/local/protoc']},
  {action = 'run', bin = 'rm', args = ['/protoc-3.11.4.zip']},
  {action = 'append', to = '/etc/profile.d/protoc.sh', data = "# Make protoc available via path\nexport PATH=$PATH:/usr/local/protoc/bin\n"},
]
